# name: Deploy to EC2

# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Deploy to EC2
#         uses: appleboy/ssh-action@master
#         with:
#           host: 3.110.55.100
#           username: ec2-user
#           key: ${{ secrets.EC2_SSH_KEY }}
#           port: 22
#           command_timeout: 30m
#           script: |
#               cd pet-co
#               git pull origin main

#               # ---------- BACKEND ----------
#               cd backend
#               mvn clean package -DskipTests
#               sudo systemctl restart petco

#               # ---------- FRONTEND ----------
#               cd ../frontend
#               npm run build

#               sudo rm -rf /var/www/html/*
#               sudo cp -r dist/* /var/www/html/

